# .streamlit/secrets.toml
[connections.snowflake]
account = "IKB37767"
user = "AGNIDAS"
password = "2026Agnivo@@29"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "smoothies"
schema = "public"
